development:
  secret_key_base: your_secret_key_for_development
  webhook_secret: your_webhook_secret_for_development

test:
  secret_key_base: your_secret_key_for_test
  webhook_secret: your_webhook_secret_for_test

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  webhook_secret: <%= ENV['WEBHOOK_SECRET'] %>
